# Day 27 Assignment (SVM) - Hitik Panchal

In [22]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import svm

# Reading the Data

In [23]:
data = pd.read_csv('train.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [24]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [25]:
data.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked       False
dtype: bool

# Converting the Data

In [26]:
data['Age'].mean()

32.69985376827896

In [27]:
data['Age'] = np.where(data['Age'].isnull(),32,data['Age'])

In [28]:
label_encoder = preprocessing.LabelEncoder()

In [29]:
data['Sex'] = label_encoder.fit_transform(data['Sex'])

In [30]:
data['Embarked'] = label_encoder.fit_transform(data['Embarked'])

In [31]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [32]:
data.drop(["PassengerId","Name","Ticket","Cabin"],axis = 1,inplace = True)

In [33]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

# Function for finding the Accuracy and Confusion Matrix

In [34]:
def conf_matrix(ydata):
    y = data[ydata]
    X = data.drop([ydata], axis = 1)
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3,random_state = 0)
    clf = svm.SVC(gamma=0.01, C=100)
    y_pred = clf.fit(X_train, y_train).predict(X_test)
    print("The Accuracy Score for "+ydata+" is : ",accuracy_score(y_test, y_pred, normalize = True))
    print()
    print("The Confusion Matrix for "+ydata+" is : ")
    print(confusion_matrix(y_test, y_pred))

# Finding the Accuracy Score and Confusion Matrix for different Dependent Variables

### DV : Survived , IDV : Remaining

In [35]:
conf_matrix("Survived")

The Accuracy Score for Survived is :  0.7415730337078652

The Confusion Matrix for Survived is : 
[[124  33]
 [ 36  74]]


### DV : Pclass , IDV : Remaining

In [36]:
conf_matrix("Pclass")

The Accuracy Score for Pclass is :  0.9026217228464419

The Confusion Matrix for Pclass is : 
[[ 64   4   2]
 [  4  36   9]
 [  1   6 141]]


### DV : Gender , IDV : Remaining

In [37]:
conf_matrix("Sex")

The Accuracy Score for Sex is :  0.7265917602996255

The Confusion Matrix for Sex is : 
[[ 66  32]
 [ 41 128]]


### DV : SibSp , IDV : Remaining

In [38]:
conf_matrix("SibSp")

The Accuracy Score for SibSp is :  0.7490636704119851

The Confusion Matrix for SibSp is : 
[[150  24   7   0   1   0   0]
 [ 21  39   5   0   0   0   0]
 [  4   1   3   0   0   0   0]
 [  0   2   1   3   1   0   0]
 [  0   0   0   0   2   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]


### DV : Parch , IDV : Remaining

In [39]:
conf_matrix("Parch")

The Accuracy Score for Parch is :  0.797752808988764

The Confusion Matrix for Parch is : 
[[187   6   5   0   0   0]
 [ 21  15   3   0   0   1]
 [ 10   6  11   0   0   0]
 [  0   0   1   0   0   0]
 [  1   0   0   0   0   0]
 [  0   0   0   0   0   0]]


### DV : Embarked , IDV : Remaining

In [40]:
conf_matrix("Embarked")

The Accuracy Score for Embarked is :  0.7677902621722846

The Confusion Matrix for Embarked is : 
[[ 23   2  24]
 [  0   8  14]
 [ 18   4 174]]
