# Day 15 Assignment - Hitik Panchal

# 1. Create a 3x3x3 Array with Random Values 

In [2]:
import numpy as np

arr = np.random.random((3,3,3))
print(arr)

[[[0.85072537 0.44078797 0.7531967 ]
  [0.34688896 0.72659313 0.55224545]
  [0.0686137  0.26504949 0.39524275]]

 [[0.64135292 0.47193496 0.76798521]
  [0.29325459 0.18261735 0.01919698]
  [0.85785917 0.18190196 0.16078718]]

 [[0.86909327 0.40928568 0.05512646]
  [0.69738529 0.65915387 0.8825752 ]
  [0.36953306 0.29056831 0.09724406]]]


# 2. Create a 5x5 Matrix with Values 1,2,3,4 just below the Diagonal

In [3]:
arr1 = np.diag(1 + np.arange(4), k = -1)
print (arr1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3. Create a 8x8 Matrix and Fill it with a Checker-board Pattern

In [4]:
arr2 = np.zeros((8,8), dtype=int)
arr2[1::2, ::2]= 1
arr2[::2, 1::2] = 1
print (arr2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 Random Matrix

In [7]:
a1 = np.random.random((5,5))
print("Original Array : \n")
print(a1)

a1_max = a1.max()
a1_min = a1.min()

a1 = (a1 - a1_min)/(a1_max - a1_min)
print("\nAfter normalization : \n")
print(a1)

Original Array : 

[[0.1848709  0.6308253  0.86153516 0.76877093 0.81891137]
 [0.97187625 0.10708069 0.3155566  0.22163858 0.39061997]
 [0.32377636 0.47001704 0.00101594 0.17577159 0.14115155]
 [0.8762608  0.25154173 0.63725662 0.04686982 0.5862585 ]
 [0.38545813 0.97701002 0.63958621 0.08359759 0.33516995]]

After normalization : 

[[0.18837713 0.64530039 0.88168488 0.78663899 0.8380127 ]
 [0.99473996 0.10867355 0.32227722 0.22604916 0.39918688]
 [0.33069916 0.48053683 0.         0.179054   0.14358244]
 [0.89677271 0.25668782 0.6518899  0.04698172 0.59963741]
 [0.39389808 1.         0.65427679 0.08461286 0.34237299]]


# 5.  How to find Common Values Between Two Arrays ?

In [10]:
c1 = np.array([0, 10, 20, 30, 40, 50])
print("Array1 : ", c1)

c2 = np.array([60, 30, 50])
print("Array2 : ", c2)

print("\nCommon values between two arrays : ")
print(np.intersect1d(c1, c2))

Array1 :  [ 0 10 20 30 40 50]
Array2 :  [60 30 50]

Common values between two arrays : 
[30 50]


# 6. How to Get the Dates of Yesterday , Today and Tomorrow ?

In [11]:
yday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday : ",yday)

today = np.datetime64('today', 'D')
print("Today : ",today)

tomo = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow : ",tomo)

Yestraday :  2020-07-26
Today :  2020-07-27
Tomorrow :  2020-07-28


# 7. Consider Two Random Array A and B, Check if they are Equal

In [18]:
arr1 = np.random.randint(0,2,6)
print("First array : ")
print(arr1)

arr2 = np.random.randint(0,2,6)
print("\nSecond array : ")
print(arr2)

array_equal = np.allclose(arr1, arr2)

if(array_equal == False):
    print("\nThe arrays are not equal..")
else:
    print("\nThe arrays are equal..")

First array : 
[0 0 1 0 1 1]

Second array : 
[0 0 1 1 1 1]

The arrays are not equal..


# 8. Create Random Vector of Size 10 and Replace the Maximum Value by 0 

In [21]:
arr = np.random.random(10)
print("Original array : \n")
print(arr)

arr[arr.argmax()] = 0
print("\nMaximum value replaced by 0 : \n")
print(arr)


Original array : 

[0.88234285 0.86405985 0.63954982 0.83042235 0.62349    0.33822449
 0.25271054 0.73329651 0.86876224 0.40223829]

Maximum value replaced by 0 : 

[0.         0.86405985 0.63954982 0.83042235 0.62349    0.33822449
 0.25271054 0.73329651 0.86876224 0.40223829]


# 9. How to Print all the Values of an Array ?

In [23]:
arr = np.random.random(10)
print("The array is : \n")
print(arr)

print("\nThe elements of the array are : \n")
for i in arr:
    print(i)

The array is : 

[0.5619436  0.53941154 0.86074312 0.9100361  0.15954302 0.4411648
 0.64819441 0.70948218 0.75329063 0.65194182]

The elements of the array are : 

0.5619436048600471
0.5394115403080163
0.8607431153524456
0.9100361044597903
0.15954301848932673
0.44116480023106697
0.6481944094876739
0.7094821835716963
0.7532906347153342
0.6519418222034523


# 10. Subtract the Mean of Each Row of a Matrix

In [24]:
arr1 = np.random.rand(2 , 5)
print("Original matrix : \n")
print(arr1)

print("\nSubtract the mean of each row of the said matrix : \n")
arr2 = arr1 - arr1.mean(axis=1, keepdims=True)
print(arr2)

Original matrix : 

[[0.77456265 0.20107012 0.53521704 0.14000961 0.23437798]
 [0.91908622 0.94732684 0.20247805 0.23237415 0.66849852]]

Subtract the mean of each row of the said matrix : 

[[ 0.39751517 -0.17597736  0.15816956 -0.23703787 -0.1426695 ]
 [ 0.32513347  0.35337408 -0.39147471 -0.36157861  0.07454577]]


# 11. Consider a Given Vector , how to Add 1 to Each Element Indexed by a Second Vector (Be Careful with Repeated Indices) ? 

In [25]:
arr1 = np.ones(10)
arr2 = np.random.randint(0,len(arr1),20)
arr1 += np.bincount(arr2, minlength=len(arr1))
print(arr1)

[2. 2. 3. 6. 1. 1. 1. 7. 4. 3.]


# 12. How to Get the Diagonal of a Dot Product ?

In [32]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

print("Array1 : \n", arr1)
print("\nArray2 : \n", arr2)

print("\nDot Product is : \n")
print(np.dot(arr1, arr2))

np.diag(np.dot(arr1, arr2))


Array1 : 
 [[8 5 2]
 [3 1 3]
 [9 8 5]]

Array2 : 
 [[7 8 2]
 [5 5 6]
 [7 8 8]]

Dot Product is : 

[[ 95 105  62]
 [ 47  53  36]
 [138 152 106]]


array([ 95,  53, 106])

# 13. How to Find the Most Frequent Value in an Array ?

In [36]:
arr = np.random.randint(0, 10, 30)
print("Original array : \n")
print(arr)

print("\nMost frequent value in the above array : ")
print(np.bincount(arr).argmax())


Original array : 

[1 5 5 0 1 8 3 2 9 8 1 2 4 0 2 9 5 6 9 9 2 1 6 6 7 1 0 9 6 8]

Most frequent value in the above array : 
1


# 14. How to Get the n Largest Values of an Array

In [44]:
arr = np.arange(10)

print("Original array : ")
print(arr)

np.random.shuffle(arr)
n = int(input("\nEnter the value of n : "))
print("\nThe ",n," largest number(s) in the array are\is : ")
print (arr[np.argsort(arr)[-n:]])

Original array : 
[0 1 2 3 4 5 6 7 8 9]

Enter the value of n : 3

The  3  largest number(s) in the array are\is : 
[7 8 9]


# 15. How to Create a Record Array from a Regular Array ?

In [46]:
a1 = np.array([1,2,3,4])
a2 = np.array(['Apple','Ball','Car','Dog'])
a3 = np.array(['Fruit','Toy','Vehicle','Animal'])
result = np.core.records.fromarrays([a1, a2, a3],names='A,B,C')

print("The record array is : ")
print(result[0])
print(result[1])
print(result[2]) 

The record array is : 
(1, 'Apple', 'Fruit')
(2, 'Ball', 'Toy')
(3, 'Car', 'Vehicle')
